[package]
name = "frame_processing_simulation"
version = "0.1.0"
edition = "2021"

[dependencies]
core_affinity = "0.8.3"
rand = "0.9.1"
rayon = "1.10.0"
tokio = { version = "1.45.0", features = ["full"] }
